---
#
# Installing Filebeat
#

# Install Filebeat 

- name: Install Filebeat with apt
  apt:
   name: filebeat
   update_cache: yes

# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
