version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.53.2
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana:11.1.1
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - TZ="Asia/Shanghai"
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./data/grafana:/var/lib/grafana
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    hostname: alertmanager
    ports:
      - "9093:9093"
    restart: always
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    environment:
      TZ: "Asia/Shanghai"
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  prom_data:
    driver: local