global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'webhook'
receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://192.168.1.10/api/v1/alerts'
        http_config:
          basic_auth:
            username: 'admin'
            password: 'P@SS1234'