version: '2'
services:
    influxdb:
      image: influxdb:latest
      container_name: influxdb
      command: mkdir -p ./data/influxdb
      ports:
        #- "8083:8083"
        - "8086:8086"
        #- "8090:8090"
      environment:
        #- INFLUXDB_DATA_ENGINE=tsm1
        #- INFLUXDB_REPORTING_DISABLED=false
        - INFLUXDB_DB=influx
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=admin
      volumes:
        # Data persistency
        # sudo mkdir -p /opt/influxdb
        - ./data/influxdb:/var/lib/influxdb2

    telegraf:
      image: telegraf:latest
      container_name: telegraf
      links:
        - influxdb
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      command: mkdir -p ./data/grafana
      ports:
        - "3000:3000"
      user: "0"
      links:
        - influxdb
      volumes:
        # Data persistency
        # sudo mkdir -p /opt/grafana
        - ./data/grafana:/var/lib/grafana